export const ErrorCodes = {
  AUTHORIZATION: {
    INVALID_BEARER: 'INVALID_BEARER',
    INVALID_TOKEN: 'INVALID_TOKEN'
  },
  INVALID_ROUTE: 'INVALID_ROUTE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
}
