version: '3.8'

services:
  # Node.js service
  blusalt_drone_api:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://blusalt_server:password123@postgres:5432/blusalt_drone_db?schema=public
      NODE_ENV: development
      PORT: 4000

  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: blusalt_server
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: blusalt_drone_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
