version: '3.8'

services:
  # Node.js service
  blusalt_drone_api:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: blusalt_server
      POSTGRES_PASSWORD: password123!
      POSTGRES_DB: blusalt_drone_db
    volumes:
      - ./blusalt_drone_api:/app

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: blusalt_server
      POSTGRES_PASSWORD: password123!
      POSTGRES_DB: blusalt_drone_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
